(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[589,598,117,126],[359,626,170,57],[0,0,970,250],[359,504,228,120],[589,504,208,92],[0,252,970,250],[0,504,357,220]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.billboardcinnamonbuns = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.billboardcranberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.billboardgetinspiredtrace = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.billboardgreens = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.billboardpotatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.billboardtable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.billboardturkey = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.wholefoodsmarket = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMCSQgMgFgJgIQgJgHgDgOQgEgNABgkIAAiBIgXAAIgGgCIgDgGIAAgGQAAgHAZgXIAKgIIAKgIQAZgWAJAAIAHACQADACgBAEIAAAtIA2AAQAGAAADACQACADAAAGIAAAGQAAAHgDADQgCACgGAAIgxAAIgEACIgCAFIAAB4QABAfAFAIQAFAIAOAAQAIAAAMgEIARgEQAEAAAEADQAEADgBAFQAAANgUANQgVAMgZAAQgOAAgMgDg");
	this.shape.setTransform(222.6,3.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhOBbQgjgjAAg0QAAg4AkgkQAjglA2AAQAvAAAcAbQAbAaAAAtQgBAPgEAFQgEAFgSAAIhcAAQgJAAgDgEQgFgEAAgHQAAgGAFgDQAEgEAHAAIAzAAIALgCQADgCABgFQgBgXgPgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlATAbQAUAcAdAAQASAAAMgEQANgEALgIIAJgHQAMgKAHAAQAFAAAEADQADAEAAAFQAAAFgFAJQgHAIgKAJQgVARgUAIQgTAHgXAAQgzAAgigjg");
	this.shape_1.setTransform(201.1,5.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABPCwIgLgBQgKgEgXgeIgKgMIgEgGQg7hMgFAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIgBAKIAAAKIABAzQACAPADADIAOAIQALAEAAAJQAAAJgMAFQgMADggAAQgkAAgMgDQgMgFAAgKQAAgIAMgFIAGgDQAHgDADgLQACgNAAgcIAAgeIAAglIAAgdIgChaQgBgWgEgEQgDgDgLgDIgIgCIgJgFIgCgHQAAgGAFgEQAFgEARgGIAggJIAZgDQAIgBADAFQADAEAAAMIgCAuIgBA/IAAA8IABAMQAAABAAAAQABABAAAAQABAAAAAAQABABAAAAIALgGIARgOIAXgXQAGgHAAgEQAAgCgJgEQgIgGAAgHQAAgKAMgFQANgEAigBQAXABALAEQAKAFAAAJQAAALgRAEQgSAFgHAEQgJAFgVAVIgEADIgIAJIgCAFQAAAFAVAbIADAEIApAyQARAUAKAHQAGAFAPAEQAQAFAAAKQAAAKgLAFQgMAFgagBg");
	this.shape_2.setTransform(175.7,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgOQgBgsgBgNQgCgOgFgDIgLgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAhgKIAVgFQANAAAEAhIAAAFIABABQANgTANgLQAOgKANAAQARAAAKAKQAKAKAAARQAAARgIAKQgHAJgOAAIgMgCIgKgHIgGgKQgDgGgCAAQgRAAgGAXQgGAXAABJQAAAVACALQACAKAHADIAKADQAOAFAAAKQAAAJgNAEQgOAEggAAQglAAgMgEg");
	this.shape_3.setTransform(152.7,5.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AArBxIgNgMIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgUQAcgWAyAAQAMAAAGAEQAGADAAAJQAAANgRABQgXgBgPAMQgOAMAAAVQAAASAMAMQANAMAVAAQAXAAAKgLQAKgKAAgaIAAhbQAAgVgJgLQgJgMgRAAQgLAAgLAGQgKAFgJAKIgFAHQgPASgQAAQgKAAgGgFQgFgHAAgKQAAgXAcgQQAcgPAsAAQAaAAATAHQATAHALAOQAHAIADAPQADAQAAAiIAABNQAAANACAIQADAGAFACIAHABQAPAEAAAJQAAAMgQAJQgQAJgWAAQgKAAgMgNg");
	this.shape_4.setTransform(130.3,5.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABbCqQgOgEAAgLQAAgKAPgFIAKgFQAFgEACgLQABgKAAghIAAgMIAAhmIgBg9IgeBQQhHC4gQAAQgIAAgOgZQgNgagjhOIg0h5IgCBfIgBBBIABAsQACAMAEADIALAFQAPAFAAAKQAAALgNAEQgNAFgdgBQgaAAgMgEQgMgFAAgKQAAgJANgGQANgGACgFQACgLAFg/QADg9AAhMIAAgIQAAgagCgIQgDgIgFgDIgLgGQgQgGAAgKQABgJAKgDQAMgEAigBIAiACIAKACQAFADARArIANAiIAHASQA7CQAEAAQAFAAAWg0QAWgzAehVIAEgPQAJgaAHgJQAEgEALgBIAggDQAhABAKAEQALADAAAJQAAALgNAEIgHADQgHAFgDAJQgCAJAAAlIACCKQADA+ACAIQABAGALAEIAFABIAJAGQADAEAAAFQAAALgNAEQgOAFgogBQgjABgNgFg");
	this.shape_5.setTransform(95.3,0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_6.setTransform(49.6,5.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhpCSQgdghAAg0QAAg7AhgkQAhglAzAAIARACQAIACAEAGQAEAFAAAGQAAANgQAAIgHgBIgGAAQgbAAgQAWQgQAVAAAmQAAApASAZQARAaAbAAQAZAAAOgOQAOgOAAgbIAAhCIAAhvQAAgRgDgGQgDgHgJgDIgHgCQgPgEAAgJQAAgGAGgFQAGgFASgGIAbgIIAXgDQAIAAAEAFQADAEAAALIAAAMIgDCVIACBlQABAXAEADIARAGQANACAAAJQAAALgjAMIgYAGIgTACQgHAAgDgEQgDgEAAgIIAAgLIAAgFIgBgCIgIAFIgKAIQgPALgNAFQgOAGgPAAQgtAAgcghg");
	this.shape_7.setTransform(25.8,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_8.setTransform(-3,5.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_9.setTransform(-30.1,5.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ah6CsQgNgEAAgKQAAgJAMgGQANgFADgDQADgFACglIAChdIgChZQgDglgCgFQgDgDgMgFQgNgFAAgKQAAgKALgEQALgDApAAICUAAIAXgCIANgDIAGACIAEADQAFAKAFAQQAEARAAALQAAALgEAGQgEAGgHAAQgIAAgKgRIgIgMQgFgHgLgEQgKgDgQAAIgiAAQgWAAgMACQgMADgEAGQgEAEgCAQIgCAuIAAAUQAAALACADQACADAHAAIAnAAQATAAAIgFQAHgGACgPIABgFQAEgZANAAQAKABAEANQAEAMAAAvQAAAtgEAOQgEAMgKAAQgNAAgEgaIgBgDQgCgQgHgFQgIgFgTgBIgnAAQgGABgDAEQgCADAAAQIAAATIACBDQABAPAFADIAKAGQAPAFAAAKQAAALgNADQgOAFglAAQgnAAgNgFg");
	this.shape_10.setTransform(-57.9,0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhOBbQgjgjAAg0QAAg4AkgkQAkglA1AAQAvAAAcAbQAbAaAAAtQAAAPgFAFQgEAFgSAAIhcAAQgJAAgEgEQgEgEAAgHQAAgGAEgDQAFgEAHAAIAyAAIAMgCQAEgCAAgFQAAgXgQgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlAUAbQATAcAdAAQASAAAMgEQANgEALgIIAJgHQAMgKAHAAQAFAAAEADQAEAEAAAFQgBAFgFAJQgHAIgKAJQgVARgTAIQgUAHgXAAQgyAAgjgjg");
	this.shape_11.setTransform(-98.9,5.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgoCuQgMgFAAgKQAAgHAKgFIAMgHQAEgEACgPIACgvIAAglIAAguIAAgTQAAg8gCgRQgDgSgFgDIgPgFQgPgFAAgIQAAgGAFgEQAEgEARgGIAhgJIAYgDQAIgBACAFQADAEAAAMIAAASQgDBWAABXIABBTQACARAEAEIANAIQAMAEAAAJQAAAJgMAFQgNADgfAAQgjAAgMgDg");
	this.shape_12.setTransform(-118.8,0);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_13.setTransform(-138.8,5.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAiCtQgMgEgBgJQABgJAMgFIAJgDQAGgEABgKQADgKAAgaQAAhOgKgSQgKgUgZAAQgMAAgMAIQgLAIgHAMQgGAKgCATQgBASAAAwQAAAYABAIQADAIAFADIAJADQAMAFAAAJQAAAJgMAEQgLAEggAAQgmAAgLgEQgMgEAAgKQAAgIAMgFIAGgDQAGgDADgKQADgKAAgbIAAgnIAAglIgBhtQgCgbgEgFQgCgDgPgEQgOgEAAgIQAAgHAGgFQAGgEAVgIIAZgHIAVgCQAJAAADAEQADAFAAALIAAAKIgCBgIAAAMIACAGIADACIAFgGIAJgKQAMgLAOgGQAMgGAPAAQAqAAAUAbQAVAagBA2IAAAWIABAsIAAANQAAANACAFQACAFAGADIAGADQAMAEAAAJQAAAKgLAEQgMAEgnAAQgfAAgLgEg");
	this.shape_14.setTransform(-167.1,0);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAhBVIgziGQgQgsgJgUQgKgUgJgHIgOgGQgMgEAAgJQAAgKAMgEQALgEAuAAQAsAAAMAEQALAEAAAKQAAAJgSAHIgDABQgFACgDADQgDAEAAAFQAAAJAMAhIAoBpIARAmQAFALAEAAQADAAAFgIIAQgkIAEgKQAyh4AAgOQAAgIgDgFQgEgFgIgEIgFgCQgPgGAAgJQAAgKAKgEQAKgEAnAAQAmAAAKAEQAKAEAAAKQAAAJgOAGIgKAFQgRALggBTIgUAxIguByIgIAVQgPAngLAAQgMAAgkhdgAhjCdIgDgHQgfhDgvh8IgXg6IgOgdQgGgKgIgEIgHgDQgPgEAAgKQAAgKALgEQALgEAuAAQAuAAALAEQALAEAAAKQAAAJgSAHIgCABQgGACgDADQgCAEAAAFQAAAIAJAdIApBqIATAsQAFAJADAAQAFAAAFgMIAMgcQAFgQANAAQAPAAAAAQIgDAPIgfBNIgHATQgPAngKAAQgIAAgJgVg");
	this.shape_15.setTransform(-206,0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wholefoodsmarket, new cjs.Rectangle(-233,-30.7,466.1,61.4), null);


(lib.trynewflavors = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape.setTransform(166.8,5.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEADgIQACgIAAgSIAAgQIgBgUIAAgOQAAgsgBgNQgCgOgFgDIgLgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAhgKIAVgFQANAAADAhIABAFIABABQAMgTAOgLQANgKAOAAQARAAAKAKQAKAKAAARQAAARgHAKQgIAJgOAAIgMgCIgKgHIgGgKQgDgGgCAAQgRAAgGAXQgGAXAABJQAAAVACALQADAKAGADIAKADQAOAFAAAKQAAAJgNAEQgOAEggAAQglAAgMgEg");
	this.shape_1.setTransform(147.9,5.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_2.setTransform(124.5,5.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgZBlQgOgXgihQIgOgjQgRgugLgGIgHgDQgOgFAAgJQAAgKAMgEQAMgEAnAAQAhAAAMAEQAMAEAAAKIgCAIIgEAEIgIADQgKAFAAAFIAFATIATAvIATAuQAGALADAAQADAAAFgGIALgWIAag8QAIgXAAgJIgCgIIgFgGIgHgDQgLgEAAgIQAAgJALgEQALgEAeAAQAZAAAKAEQAKAEAAAJQAAAKgMAEIgIADQgMAFgUAwIgGAPIgKAWQg3B9gPAAQgLAAgNgYg");
	this.shape_3.setTransform(98.5,5.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AArBxIgNgMIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgUQAcgWAyAAQAMAAAGAEQAGADAAAJQAAANgRABQgXgBgPAMQgOAMAAAVQAAASAMAMQANAMAVAAQAXAAAKgLQAKgKAAgaIAAhbQAAgVgJgLQgJgMgRAAQgLAAgLAGQgKAFgJAKIgFAHQgPASgQAAQgKAAgGgFQgFgHAAgKQAAgXAcgQQAcgPAsAAQAaAAATAHQATAHALAOQAHAIADAPQADAQAAAiIAABNQAAANACAIQADAGAFACIAHABQAPAEAAAJQAAAMgQAJQgQAJgWAAQgKAAgMgNg");
	this.shape_4.setTransform(73.3,5.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpCuQgLgFAAgKQAAgHAKgFIAMgHQAEgEACgPIACgvIgBglIAAguIAAgTQAAg8gCgRQgCgSgFgDIgPgFQgPgFAAgIQAAgGAFgEQAFgEARgGIAggJIAYgDQAHgBADAFQAEAEAAAMIgBASQgDBWAABXIABBTQACARAEAEIAOAIQALAEAAAJQAAAJgMAFQgNADgfAAQgkAAgMgDg");
	this.shape_5.setTransform(53,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ah6CsQgNgEAAgKQAAgJAMgGQANgFADgDQADgFACglIAChdIgChZQgDglgCgFQgDgDgMgFQgNgFAAgKQAAgKALgEQALgDApAAICUAAIAXgCIANgDIAGACIAEADQAFAKAFAQQAEARAAALQAAALgEAGQgEAGgHAAQgIAAgKgRIgIgMQgFgHgLgEQgKgDgQAAIgiAAQgWAAgMACQgMADgEAGQgEAEgCAQIgCAuIAAAUQAAALACADQACADAHAAIAnAAQATAAAIgFQAHgGACgPIABgFQAEgZANAAQAKABAEANQAEAMAAAvQAAAtgEAOQgEAMgKAAQgNAAgEgaIgBgDQgCgQgHgFQgIgFgTgBIgnAAQgGABgDAEQgCADAAAQIAAATIACBDQABAPAFADIAKAGQAPAFAAAKQAAALgNADQgOAFglAAQgnAAgNgFg");
	this.shape_6.setTransform(32.3,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAOAaIgdhLQgNgigMgGIgHgDQgOgFAAgJQAAgKAMgEQAMgEAnAAQAhAAALAEQAMAEAAAKIgCAHIgEAFIgIADQgKAFAAAFIAEAQIAUAyIAVAuQAFALADAAQAEAAAEgGIALgWIAag8QAJgXAAgJIgCgIIgGgGIgHgDQgKgEAAgIQAAgJAKgEQALgEAeAAQAZAAALAEQAKAEAAAJQAAAKgNAEIgIADQgLAGgWAyIgFAMIgKAWQg3B9gQAAQgQAAgrhjgAiNAOIgHgQIgQgoQgQgpgKgGIgIgDQgOgFAAgJQAAgKANgEQAMgEAnAAQAhAAALAEQAMAEAAAKIgBAIIgFAEIgIADQgKAFAAAFIAGAUIASAuIAUAtQAGAMADAAQAIAAAGgPIAJgRIAFgHQADgDAFAAQAGAAAEADQADAEAAAGQAAAGgHAOQgZA3gLATQgLASgJAAQgRAAgvhvg");
	this.shape_7.setTransform(-15.5,5.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhOBbQgigjgBg0QAAg4AkgkQAjglA2AAQAvAAAbAbQAbAaAAAtQAAAPgDAFQgFAFgSAAIhcAAQgJAAgDgEQgFgEAAgHQAAgGAFgDQADgEAIAAIAzAAIALgCQADgCAAgFQAAgXgPgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlATAbQATAcAfAAQARAAAMgEQANgEAMgIIAIgHQANgKAGAAQAGAAADADQAEAEgBAFQAAAFgFAJQgHAIgKAJQgVARgUAIQgTAHgXAAQgzAAgigjg");
	this.shape_8.setTransform(-48.4,5.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ah2B4QgMgEAAgLQAAgIAMgFIAGgCQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgYQAAgmgCgLQgCgMgFgDIgLgEQgPgEAAgJQAAgFAFgEQAFgEAKgFIAjgLIAZgEQAHAAADAEQADADAAAIIAAAQIAAADIABAAIACAAIABgBIAFgFIAFgEQAbgZAdAAQASAAAQAIQAQAHALANQALANAFATQAEASAAAnIAAAgIAAAPIAAAOQAAARACAIQADAGAGAEIAGACQAMAFAAAIQAAAKgLAEQgLAEglAAQgiAAgMgDQgLgEAAgJQAAgKAMgEIAJgEQAFgDADgKQACgLAAgaQAAhMgKgUQgKgTgZAAQgMAAgMAIQgMAHgGANQgFALgCASQgCATAAAvQAAAYACAIQACAHAFADIAJAEQAMAEAAAKQAAAJgMAEQgMAEgfAAQglAAgMgEg");
	this.shape_9.setTransform(-75.6,5.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhvCgQgLgKAAgQQAAgMAIgIQAJgJALAAIALACIAHAFIAHAJQAHAKAEAAQAMAAANgSQAMgSAAgTQAAgVgRgmIgCgGIgmhUIgXgvQgEgIgOgGQgJgEgCgDQgDgDAAgGQAAgKAMgEQANgFAjAAQAkAAAMAEQALAEABAKIgCAHIgFAFIgJAEQgIAEgBAEIAGASIATAwIATAuQAGALADAAQADAAAFgLIARgmIARgwQAGgRAAgGQAAgHgOgIQgOgIAAgGQAAgIAMgEQAKgEAcAAQAdAAAKAEQAKAEAAAKQAAAJgNADIgKAEQgOAHgPApIgHATIgfBNQgoBkgZAeQgZAfgkAAQgRAAgMgKg");
	this.shape_10.setTransform(-115.2,10.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEADgIQACgIAAgSIAAgQIgBgUIAAgOQAAgsgBgNQgCgOgGgDIgKgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAhgKIAVgFQANAAADAhIABAFIABABQAMgTAOgLQANgKAOAAQARAAAKAKQAKAKAAARQAAARgHAKQgIAJgOAAIgMgCIgKgHIgGgKQgDgGgCAAQgRAAgGAXQgGAXAABJQAAAVACALQADAKAGADIAKADQAOAFAAAKQAAAJgNAEQgOAEggAAQglAAgMgEg");
	this.shape_11.setTransform(-136.1,5.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgyCrQgOgDAAgLQAAgKANgFQAOgFACgDQADgEABgoIAChyIgChAIgCgnQgBgGgDgCQgFgCgKAAIgKAAQgRAAgJAEQgJAEgHAKIgIAQIgGAQIgHAHQgFADgEABQgHAAgDgHQgEgGAAgQQAAgfAHgTQAIgUALAAIAEAAQASADAdAAICOAAQAeAAASgDIAEAAQALAAAIAUQAHATAAAfQAAAQgEAGQgDAHgHAAIgJgEIgHgHIgHgQIgHgQQgHgKgJgEQgKgEgQAAIgKAAQgKAAgFACQgDACgBAHIgDAmIgBBAIACByQABAoADAEQADADANAFQANAFAAAKQAAALgOADQgOAFglAAQgkAAgOgFg");
	this.shape_12.setTransform(-161.6,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.trynewflavors, new cjs.Rectangle(-179.4,-30.7,358.9,61.4), null);


(lib.thanksgiving = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhZCdQgfgSAAgbQAAgMAHgIQAGgIAOAAQAKAAAFAGQAGAGADALQAGARAPALQAPAKAeAAQAfAAAVgNQAWgMAAgTQAAgLgIgGQgIgHgPAAIgcADIglACQgrAAgXgPQgXgOAAgUQAAgMAIgLQAJgLARgLQgOgMgHgQQgHgQAAgSQAAgoAegaQAdgaAuAAIAYACIAmAIQAIAAALgEQAKgFAQgLIAHAIIADAIQAAAKgIAKQgHAJgOAIIAHATIACAUQAAAogdAaQgdAXgvAAIgZgCIgXgEIgIAJIgCAJQAAALALAFQAMAGAYAAIAkgCIAlgEQAiAAASAOQASAOAAAZQAAAngmAaQgmAZg5AAQguABgfgUgAgnh4QgNAQAAAYQAAAZANAPQAMAPAUAAQATAAAOgPQANgPAAgYQAAgagNgPQgNgPgUAAQgTAAgNAPg");
	this.shape.setTransform(135.6,9.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ah2B4QgMgEAAgLQAAgIAMgFIAGgCQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgYQAAgmgCgLQgCgMgFgDIgLgEQgPgEAAgJQAAgFAFgEQAFgEAKgFIAjgLIAZgEQAHAAADAEQADADAAAIIAAAQIAAADIABAAIACAAIABgBIAFgFIAFgEQAbgZAdAAQASAAAQAIQAQAHALANQALANAFATQAEASAAAnIAAAgIAAAPIAAAOQAAARACAIQADAGAGAEIAGACQAMAFAAAIQAAAKgLAEQgLAEglAAQgiAAgMgDQgLgEAAgJQAAgKAMgEIAJgEQAFgDADgKQACgLAAgaQAAhMgKgUQgKgTgZAAQgMAAgMAIQgMAHgGANQgFALgCASQgCATAAAvQAAAYACAIQACAHAFADIAJAEQAMAEAAAKQAAAJgMAEQgMAEgfAAQglAAgMgEg");
	this.shape_1.setTransform(107.5,5.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgqCtQgMgFAAgKQAAgIALgFIAHgDQAGgDACgIQADgIAAgTIAAgQIAAgTIAAgZQAAgmgCgLQgCgMgFgCIgLgEQgPgEAAgJQAAgFAFgFQAEgEALgEIAkgMIAZgEQAGAAAEAEQACAFAAALIAAAPIAAALIgCA8IAAACIgBA7QAAAXACAKQACAJAGADIAJAEQAMAEAAAJQAAAJgMAFQgMADgfAAQglAAgLgDgAgdh5QgKgIAAgNQAAgOALgKQALgKAQAAQAPAAALAJQAKAJAAANQAAAOgLAJQgLAJgQAAQgQAAgKgIg");
	this.shape_2.setTransform(86.2,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgZBlQgOgXgihQIgOgjQgRgugLgGIgHgDQgOgFAAgJQAAgKAMgEQAMgEAnAAQAhAAAMAEQAMAEAAAKIgCAIIgEAEIgIADQgKAFAAAFIAFATIATAvIATAuQAGALADAAQADAAAFgGIALgWIAag8QAIgXAAgJIgCgIIgFgGIgHgDQgLgEAAgIQAAgJALgEQALgEAeAAQAZAAAKAEQAKAEAAAJQAAAKgMAEIgIADQgMAFgUAwIgGAPIgKAWQg3B9gPAAQgLAAgNgYg");
	this.shape_3.setTransform(67,5.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgqCtQgMgFAAgKQAAgIAMgFIAGgDQAGgDADgIQACgIAAgTIAAgQIAAgTIAAgZQAAgmgCgLQgCgMgFgCIgLgEQgPgEAAgJQAAgFAFgFQAEgEAKgEIAlgMIAZgEQAGAAADAEQADAFAAALIAAAPIgBALIgBA8IAAACIgBA7QAAAXACAKQACAJAFADIAJAEQANAEAAAJQAAAJgMAFQgMADggAAQgjAAgMgDgAgdh5QgLgIAAgNQAAgOAMgKQALgKARAAQAOAAALAJQAKAJAAANQAAAOgLAJQgMAJgQAAQgPAAgKgIg");
	this.shape_4.setTransform(47.5,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhZCdQgfgSAAgbQAAgMAHgIQAGgIAOAAQAKAAAFAGQAGAGADALQAGARAPALQAPAKAeAAQAfAAAVgNQAWgMAAgTQAAgLgIgGQgIgHgPAAIgcADIglACQgrAAgXgPQgXgOAAgUQAAgMAIgLQAJgLARgLQgOgMgHgQQgHgQAAgSQAAgoAegaQAdgaAuAAIAYACIAmAIQAIAAALgEQAKgFAQgLIAHAIIADAIQAAAKgIAKQgHAJgOAIIAHATIACAUQAAAogdAaQgdAXgvAAIgZgCIgXgEIgIAJIgCAJQAAALALAFQAMAGAYAAIAkgCIAlgEQAiAAASAOQASAOAAAZQAAAngmAaQgmAZg5AAQguABgfgUgAgnh4QgNAQAAAYQAAAZANAPQAMAPAUAAQATAAAOgPQANgPAAgYQAAgagNgPQgNgPgUAAQgTAAgNAPg");
	this.shape_5.setTransform(28.9,9.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_6.setTransform(4.7,5.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABPCwIgLgBQgKgEgXgeIgKgMIgEgGQg7hMgFAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIgBAKIAAAKIABAzQACAPADADIAOAIQALAEAAAJQAAAJgMAFQgMADggAAQgkAAgMgDQgMgFAAgKQAAgIAMgFIAGgDQAHgDADgLQACgNAAgcIAAgeIAAglIAAgdIgChaQgBgWgEgEQgDgDgLgDIgIgCIgJgFIgCgHQAAgGAFgEQAFgEARgGIAggJIAZgDQAIgBADAFQADAEAAAMIgCAuIgBA/IAAA8IABAMQAAABAAAAQABABAAAAQABAAAAAAQABABAAAAIALgGIARgOIAXgXQAGgHAAgEQAAgCgJgEQgIgGAAgHQAAgKAMgFQANgEAigBQAXABALAEQAKAFAAAJQAAALgRAEQgSAFgHAEQgJAFgVAVIgEADIgIAJIgCAFQAAAFAVAbIADAEIApAyQARAUAKAHQAGAFAPAEQAQAFAAAKQAAAKgLAFQgMAFgagBg");
	this.shape_7.setTransform(-18.3,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ah2B4QgMgEAAgLQAAgIAMgFIAGgCQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgYQAAgmgCgLQgCgMgFgDIgLgEQgPgEAAgJQAAgFAFgEQAFgEAKgFIAjgLIAZgEQAHAAADAEQADADAAAIIAAAQIAAADIABAAIACAAIABgBIAFgFIAFgEQAbgZAdAAQASAAAQAIQAQAHALANQALANAFATQAEASAAAnIAAAgIAAAPIAAAOQAAARACAIQADAGAGAEIAGACQAMAFAAAIQAAAKgLAEQgLAEglAAQgiAAgMgDQgLgEAAgJQAAgKAMgEIAJgEQAFgDADgKQACgLAAgaQAAhMgKgUQgKgTgZAAQgMAAgMAIQgMAHgGANQgFALgCASQgCATAAAvQAAAYACAIQACAHAFADIAJAEQAMAEAAAKQAAAJgMAEQgMAEgfAAQglAAgMgEg");
	this.shape_8.setTransform(-47.1,5.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AArBxIgNgMIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgUQAcgWAyAAQAMAAAGAEQAGADAAAJQAAANgRABQgXgBgPAMQgOAMAAAVQAAASAMAMQANAMAVAAQAXAAAKgLQAKgKAAgaIAAhbQAAgVgJgLQgJgMgRAAQgLAAgLAGQgKAFgJAKIgFAHQgPASgQAAQgKAAgGgFQgFgHAAgKQAAgXAcgQQAcgPAsAAQAaAAATAHQATAHALAOQAHAIADAPQADAQAAAiIAABNQAAANACAIQADAGAFACIAHABQAPAEAAAJQAAAMgQAJQgQAJgWAAQgKAAgMgNg");
	this.shape_9.setTransform(-74,5.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAhCtQgLgEgBgJQABgJALgFIAKgDQAFgEACgKQACgKABgaQAAhOgKgSQgKgUgZAAQgMAAgMAIQgMAIgGAMQgFAKgDATQgBASAAAwQAAAYABAIQACAIAGADIAJADQAMAFAAAJQAAAJgMAEQgMAEgfAAQgmAAgLgEQgMgEAAgKQAAgIAMgFIAGgDQAGgDADgKQADgKAAgbIAAgnIAAglIgChtQgBgbgEgFQgCgDgPgEQgOgEAAgIQAAgHAGgFQAFgEAWgIIAZgHIAVgCQAJAAADAEQADAFABALIgBAKIgCBgIAAAMIACAGIADACIAFgGIAJgKQAMgLAOgGQAMgGAPAAQAqAAAUAbQAVAaAAA2IAAAWIAAAsIAAANQAAANACAFQACAFAGADIAGADQAMAEAAAJQAAAKgLAEQgMAEgnAAQgfAAgMgEg");
	this.shape_10.setTransform(-101.9,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgyCrQgOgDAAgLQAAgKANgFQAOgFACgDQADgEABgoIABhyIgBhAIgCgnQAAgGgFgCQgDgCgKAAIgLAAQgQAAgKAEQgJAEgHAKIgIAQIgHAQIgGAHQgFADgEABQgHAAgDgHQgEgGAAgQQAAgfAHgTQAIgUALAAIADAAQAUADAdAAICNAAQAeAAASgDIADAAQAMAAAHAUQAIATAAAfQAAAQgDAGQgEAHgHAAIgIgEIgIgHIgHgQIgIgQQgGgKgJgEQgKgEgQAAIgKAAQgLAAgEACQgDACgCAHIgCAmIgBBAIACByQACAoACAEQADADANAFQANAFAAAKQAAALgOADQgNAFgmAAQglAAgNgFg");
	this.shape_11.setTransform(-131.6,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thanksgiving, new cjs.Rectangle(-149.5,-30.7,299,61.4), null);


(lib.tastingeventnearyou = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZBIQgLgFgJgIQgJgJgFgLQgDgGgBgGIgCgOIABgoIAAgoQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAAAgBIAFgCIAFgBIAFAAIAHACQADACAAADIAABMQAAAIACAIQADAIAFAGQAEAGAIADQAHAEAIAAQAJAAAHgEQAIgDAEgGQAGgGACgIQADgIAAgIIAAhMQAAgEADgCIAHgBIAEgBIAHABIAEACQACACAAAEIAABQIgCAOIgDAMQgGALgJAJQgIAIgNAFQgLAFgOAAQgNAAgMgFg");
	this.shape.setTransform(135.7,-0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgPBLQgIgBgHgDQgHgDgGgEQgHgEgFgFQgLgLgGgOQgDgHgBgHQgCgIAAgIQAAgHACgIQABgHADgHQAGgOALgLQAFgFAHgEQAGgEAHgDIAPgEQAHgCAIAAQAIAAAIACIAPAEQAPAGAKAKQALALAGAOQAGAOAAAPQAAAIgCAIQgBAHgDAHQgGAOgLALQgKAKgPAGQgHADgIABIgQACQgIAAgHgCgAgSguQgJAEgHAHQgHAHgFAJQgDAJAAAKQAAALADAJQAFAJAHAHQAHAHAJAEQAJAEAJAAQAKAAAJgEQAJgEAHgHQAHgHAFgJQADgJAAgLQAAgKgDgJQgFgJgHgHQgHgHgJgEQgJgEgKAAQgJAAgJAEg");
	this.shape_1.setTransform(118.8,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgFBNIgEgBIgCgCIgBgDIAAg0QAAgEgCgEIgEgIIgqhBIAAgCQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAIAEgEIAGgDIAFAAIAEABIAEACIAdAwIADADIADABIADgBIADgCIAegxIAEgDIAFgBIAEABIAGACIAFADQAAABAAAAQABABAAAAQAAABAAABQAAAAAAABIAAABIAAACIgrBBIgDAJIgBADIgBADIAAA1QgCAFgFABIgIAAg");
	this.shape_2.setTransform(103.4,-0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAlBLIgDgBIgDgCIgCgBIgZgnIgEgFQgDgCgEAAIgSAAQgDAAgDACQgCACAAADIAAAlQAAAAAAABQAAAAAAABQgBABAAAAQgBAAAAABIgFABIgGABIgFAAQgEAAgDgCQgCgCAAgFIAAiHQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAAAQABAAABAAIA+AAQALAAAKADQAJAEAHAGQAHAHAEAJQAEAJAAAMQAAAMgEAIQgFAHgGAFIgKAIQgFADAAADIAAADIAGAIIAJAMIAHAMQAEAGAAACQAAAAAAABQAAABgBAAQAAABAAAAQgBABAAAAIgFADIgFACIgFABgAgegvQgDACAAAEIAAAhQAAAEADACQADACAEAAIAeAAQAFAAAFgBQAFgCAEgDQAEgDACgEQACgFAAgGQAAgMgIgHQgEgDgFgBIgKgBIgeAAIgHABg");
	this.shape_3.setTransform(83.4,-0.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA6BLIgEAAIgIgBQgEgBgBgEIgJgUIgCgDIgEgBIgxAAIgCAAIgDACIgCABIgBABIgIAUIgDADIgEABIgFABIgEAAIgDAAIgFAAIgEgCQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIA9iLQAAAAAAgBQABAAAAAAQABgBAAAAQABAAABgBIAEgBIAGABQAEABABACIA7CLIAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAIgEACgAgBgWIgBABIgCAEIgDAHIgEAJIgDAHIgDAHIgBADIABADQAAABABAAQAAAAAAAAQABABAAAAQABAAAAAAIAdAAIADgCIABgDIgCgGIgFgLIgFgNIgDgHQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAg");
	this.shape_4.setTransform(68,-0.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgyBKIgEgCQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiHQAAgBAAAAQAAgBABgBQAAAAAAAAQABgBABAAIAEgCIBnAAIADADIABAFIABAEIAAAFIgCAFQAAADgDABIhNAAQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAAAABQgBAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIAAAUQAAADACACQABABADAAIAyAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABIACAFIAAAGIAAADQABAGgGACIgwAAQgCAAgDADQgCACAAADIAAAWQAAAEACABQABACADAAIBMAAQAEADAAAGIAAAEIAAAGIgCAFQAAAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_5.setTransform(54.4,-0.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AArBNQgDAAgCgFIg9hTQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQAAABgBAAQAAABAAAAQAAABAAAAIAABMQgCAEgDABQgDABgFABIgIgBQgEgBgCgFIAAiMQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIAEgCIAFAAIAFgBQAGAAAEAFIA8BQIADABIADgBQABAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAIAAhLIADgEIAFgCIAFAAIAFAAQAHAAACAHIAACMQgCADgCACIgGABg");
	this.shape_6.setTransform(38.7,-0.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgBBKIgIgBQgDgCAAgEIAAhtQgBgDgCgBQgBgCgFAAIgMAAIgLAAIgGAAQgEAAgCgEIgBgHIAAgEIABgFIACgEQAAAAAAgBQABAAAAAAQABAAABAAQAAAAABAAIBmAAQAEgBABAEQACADAAAEIAAADIgCAGIgCAEQAAABAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAIgdAAQgEAAgCACQgCABAAAEIAABsQAAADgCACIgEACIgGAAg");
	this.shape_7.setTransform(18.5,-0.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AArBNQgDAAgCgFIg9hTQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQAAABgBAAQAAABAAAAQAAABAAAAIAABMQgCAEgDABQgDABgFABIgIgBQgEgBgCgFIAAiMQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIAEgCIAFAAIAFgBQAGAAAEAFIA8BQIADABIADgBQABAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAIAAhLIADgEIAFgCIAFAAIAFAAQAHAAACAHIAACMQgCADgCACIgGABg");
	this.shape_8.setTransform(4.6,-0.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgyBKIgEgCQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiHQAAgBAAAAQAAgBABgBQAAAAAAAAQABgBABAAIAEgCIBnAAIADADIABAFIABAEIAAAFIgCAFQgBADgCABIhNAAQAAAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABQgBAAAAABQgBAAAAABQAAAAAAABQgBAAAAABIAAAUQAAADADACQACABACAAIAyAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABIACAFIAAAGIAAADQABAGgGACIgwAAQgDAAgCADQgDACAAADIAAAWQAAAEADABQABACADAAIBMAAQAEADAAAGIAAAEIAAAGIgBAFQgBAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_9.setTransform(-9.7,-0.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgCBIIgEgJIgIgRIgJgVIgKgYIgKgWIgJgVIgGgOIgCgHQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAGgDIAFgCIAFAAIAGABQADACABADIAeBKIACACIABABQADAAABgDIAfhKQABgDACgCQADgCAEAAIAEAAIAGACIAFADQAAABABAAQAAABAAAAQAAABAAABQABAAAAABIgDAGIgGAPIgIAUIgLAXIgKAYIgKAWIgHARIgEAJIgBACIgCABQAAAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBg");
	this.shape_10.setTransform(-24.1,-0.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgxBKIgFgCQgDgCAAgCIAAiHQAAgBAAAAQAAgBABgBQAAAAAAAAQABgBAAAAIAFgCIBnAAIAEADIABAFIAAAEIAAAFIgBAFQgCADgCABIhMAAQgBAAgBAAQAAABgBAAQAAAAgBABQAAAAgBABQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIAAAUQAAADABACQACABAEAAIAwAAQABAAAAAAQABABAAAAQABAAAAABQAAAAABABIABAFIABAGIAAADQgBAGgFACIgwAAQgCAAgDADQgDACABADIAAAWQAAAEABABQACACAEAAIBKAAQAFADABAGIAAAEIgBAGIgCAFQAAAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_11.setTransform(-37.1,-0.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgMBLQgHgBgHgDQgHgDgHgEIgLgJIgKgLQgEgHgDgHQgHgOAAgQQAAgIABgHQACgIAEgHQAFgOAMgKQAFgFAGgEQAHgFAHgDIAOgDQAIgCAHAAQAJAAAJACQAIABAIAEQAPAGAMAOIABADQAAACgCACIgGAGIgFAEIgFACQgDAAgEgDIgIgHQgEgEgHgDQgHgDgLAAQgJAAgJAEQgJAEgIAHQgHAHgDAJQgFAJAAAKQAAAKAFAJQADAJAHAIQAIAGAJAFQAJAEAJAAIALgBIAKgCIAJgFQAEgEADgEIAAgCQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgGgBIgaAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAIgBgFIAAgFIAAgFIABgGQAAgCADgBIA+AAIADABIACACQADAGAAAIIgBAGIAAAGQgFALgHAIQgIAKgJAFQgJAHgLACQgLAEgMAAIgPgCg");
	this.shape_12.setTransform(-60.2,-0.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AArBNQgDAAgCgFIg9hTQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQAAABgBAAQAAABAAAAQAAABAAAAIAABMQgCAEgDABQgDABgFABIgIgBQgEgBgCgFIAAiMQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIAEgCIAFAAIAFgBQAGAAAEAFIA8BQIADABIADgBQABAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAIAAhLIADgEIAFgCIAFAAIAFAAQAHAAACAHIAACMQgCADgCACIgGABg");
	this.shape_13.setTransform(-76.4,-0.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgEBNQgGgBgDgEIAAiPQABAAAAgBQABAAAAgBQAAAAABAAQABAAAAgBIAFgBIAFAAIAFAAQAGAAACAFIAACNQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBABIgFABIgFABg");
	this.shape_14.setTransform(-87.5,-0.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgCBKIgHgBQgDgCAAgEIAAhtQAAgDgCgBQgCgCgFAAIgMAAIgLAAIgGAAQgEAAgCgEIgBgHIAAgEIAAgFIACgEQABAAAAgBQABAAAAAAQABAAABAAQAAAAABAAIBlAAQAEgBACAEQABADABAEIAAADIgBAGIgCAEQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAIgdAAQgEAAgCACQgDABABAEIAABsQgBADgBACIgFACIgEAAg");
	this.shape_15.setTransform(-96.8,-0.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AggBHQgQgGgMgLIgCgDIAAgDQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAIAEgGIAFgDIAFgCQAEAAADADIAKAGIAMAGQAIADAJAAIALgBQAGAAAFgDQAGgDADgEQAEgEAAgHQAAgGgEgEQgEgDgHgCIgQgDIgQgCIgRgEQgJgCgHgEQgGgEgEgIQgEgHAAgMQAAgLAFgJQAGgIAJgFQAJgGALgCQALgDAJAAIAOABIAPAEQAHABAHAFQAGADAFAFIACACIAAADQAAADgCACIgEAFIgGADIgGACIgEgBQgIgHgIgEQgJgEgKAAIgKABQgFABgFACQgEADgEADQgDAEAAAGQAAAJAHADQAHADALACIAWADQAMACALAEQAKAEAHAHQAHAJAAAOQAAAOgGAIQgGAKgJAGQgKAGgLADQgMADgKAAQgQAAgPgGg");
	this.shape_16.setTransform(-110.2,-0.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AA6BLIgEAAIgIgBQgEgBgBgEIgJgUIgCgDIgEgBIgxAAIgCAAIgDACIgCABIgBABIgIAUIgDADIgEABIgFABIgEAAIgDAAIgFAAIgEgCQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIA9iLQAAAAAAgBQABAAAAAAQABgBAAAAQABAAABgBIAEgBIAGABQAEABABACIA7CLIAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAIgEACgAgBgWIgBABIgCAEIgDAHIgEAJIgDAHIgDAHIgBADIABADQAAABABAAQAAAAAAAAQABABAAAAQABAAAAAAIAdAAIADgCIABgDIgCgGIgFgLIgFgNIgDgHQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAg");
	this.shape_17.setTransform(-124.5,-0.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBKIgIgBQgEgCAAgEIAAhtQAAgDgCgBQgBgCgGAAIgLAAIgLAAIgGAAQgFAAgBgEIgCgHIAAgEIACgFIACgEQAAAAAAgBQABAAAAAAQABAAABAAQAAAAABAAIBmAAQAEgBABAEQABADAAAEIAAADIgBAGIgCAEQAAABAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAIgdAAQgEAAgCACQgDABAAAEIAABsQAAADgBACIgEACIgGAAg");
	this.shape_18.setTransform(-137.7,-0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tastingeventnearyou, new cjs.Rectangle(-146,-12.8,292.1,25.7), null);


(lib.savorysides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape.setTransform(128.9,5.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhOBbQgjgjAAg0QAAg4AkgkQAkglA1AAQAvAAAcAbQAbAaAAAtQAAAPgFAFQgEAFgSAAIhcAAQgJAAgEgEQgEgEAAgHQAAgGAEgDQAFgEAHAAIAyAAIAMgCQAEgCAAgFQAAgXgQgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlAUAbQATAcAdAAQASAAAMgEQANgEALgIIAJgHQAMgKAHAAQAFAAAEADQAEAEAAAFQgBAFgFAJQgHAIgKAJQgVARgTAIQgUAHgXAAQgyAAgjgjg");
	this.shape_1.setTransform(105.8,5.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhpCSQgdghAAg0QAAg7AhgkQAhglAzAAIARACQAIACAEAGQAEAFAAAGQAAANgQAAIgHgBIgGAAQgbAAgQAWQgQAVAAAmQAAApASAZQARAaAbAAQAZAAAOgOQAOgOAAgbIAAhCIAAhvQAAgRgDgGQgDgHgJgDIgHgCQgPgEAAgJQAAgGAGgFQAGgFASgGIAbgIIAXgDQAIAAAEAFQADAEAAALIAAAMIgDCVIACBlQABAXAEADIARAGQANACAAAJQAAALgjAMIgYAGIgTACQgHAAgDgEQgDgEAAgIIAAgLIAAgFIgBgCIgIAFIgKAIQgPALgNAFQgOAGgPAAQgtAAgcghg");
	this.shape_2.setTransform(79.6,0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgqCtQgMgFAAgKQAAgIALgFIAHgDQAGgDADgIQACgIAAgTIAAgQIAAgTIAAgZQAAgmgCgLQgCgMgFgCIgLgEQgPgEAAgJQAAgFAFgFQAEgEAKgEIAlgMIAZgEQAGAAADAEQADAFAAALIAAAPIgBALIgBA8IAAACIgBA7QAAAXACAKQACAJAFADIAJAEQANAEAAAJQAAAJgMAFQgMADggAAQgkAAgLgDgAgdh5QgLgIAAgNQAAgOAMgKQALgKARAAQAOAAALAJQAKAJAAANQAAAOgLAJQgLAJgRAAQgPAAgKgIg");
	this.shape_3.setTransform(57.5,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag7CuQgbgFgRgLQgKgFgGgVQgGgVAAgbQAAgLAEgGQAEgGAIABQAMAAALAVIAGAKQAQAbASANQASALAZABQAaAAASgQQASgPAAgXQAAgjhHgfIgHgDQg7gZgTgWQgTgVAAgiQAAgrAggcQAggcAzAAIAcACIAhAIIAKgHIAIgCQAGAAAFAEQAEAEAFAJQAIAPAFAPQAFAQAAAMQAAAJgEAEQgEAFgHgBQgMAAgNgRIgDgEQgOgTgQgIQgQgIgUAAQgaAAgQAMQgPAMAAAWQAAAUANAOQAMANA0AWIAKAEQArASATAQQANANAHAQQAHARAAASQAAAygiAcQgjAbg8AAQgdAAgbgGg");
	this.shape_4.setTransform(36.6,0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhvCgQgLgKAAgQQAAgMAIgIQAIgJAMAAIALACIAHAFIAHAJQAGAKAFAAQAMAAANgSQAMgSAAgTQABgVgSgmIgCgGIgmhUIgXgvQgEgIgOgGQgJgEgDgDQgCgDAAgGQAAgKAMgEQANgFAjAAQAkAAAMAEQAMAEgBAKIgBAHIgFAFIgJAEQgIAEgBAEIAGASIATAwIATAuQAGALADAAQADAAAFgLIARgmIARgwQAGgRAAgGQAAgHgOgIQgNgIAAgGQgBgIAMgEQALgEAbAAQAdAAAKAEQALAEAAAKQAAAJgOADIgKAEQgOAHgPApIgHATIgfBNQgoBkgZAeQgaAfgjAAQgRAAgMgKg");
	this.shape_5.setTransform(-2.6,10.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEADgIQACgIAAgSIAAgQIgBgUIAAgOQABgsgCgNQgCgOgGgDIgKgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAhgKIAVgFQAMAAAEAhIABAFIACABQALgTAOgLQANgKAOAAQARAAAKAKQAKAKAAARQAAARgHAKQgJAJgNAAIgMgCIgKgHIgGgKQgDgGgCAAQgRAAgHAXQgFAXAABJQAAAVACALQADAKAGADIAKADQAOAFAAAKQAAAJgNAEQgNAEghAAQglAAgMgEg");
	this.shape_6.setTransform(-23.5,5.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_7.setTransform(-46.9,5.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgZBlQgOgXgihQIgOgjQgRgugLgGIgHgDQgOgFAAgJQAAgKAMgEQAMgEAnAAQAhAAAMAEQAMAEAAAKIgCAIIgEAEIgIADQgKAFAAAFIAFATIATAvIATAuQAGALADAAQADAAAFgGIALgWIAag8QAIgXAAgJIgCgIIgFgGIgHgDQgLgEAAgIQAAgJALgEQALgEAeAAQAZAAAKAEQAKAEAAAJQAAAKgMAEIgIADQgMAFgUAwIgGAPIgKAWQg3B9gPAAQgLAAgNgYg");
	this.shape_8.setTransform(-72.9,5.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AArBxIgNgMIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgUQAcgWAyAAQAMAAAGAEQAGADAAAJQAAANgRABQgXgBgPAMQgOAMAAAVQAAASAMAMQANAMAVAAQAXAAAKgLQAKgKAAgaIAAhbQAAgVgJgLQgJgMgRAAQgLAAgLAGQgKAFgJAKIgFAHQgPASgQAAQgKAAgGgFQgFgHAAgKQAAgXAcgQQAcgPAsAAQAaAAATAHQATAHALAOQAHAIADAPQADAQAAAiIAABNQAAANACAIQADAGAFACIAHABQAPAEAAAJQAAAMgQAJQgQAJgWAAQgKAAgMgNg");
	this.shape_9.setTransform(-98.1,5.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag7CuQgbgFgRgLQgKgFgGgVQgGgVAAgbQAAgLAEgGQAEgGAIABQAMAAALAVIAGAKQAQAbASANQASALAZABQAaAAASgQQASgPAAgXQAAgjhHgfIgHgDQg7gZgTgWQgTgVAAgiQAAgrAggcQAggcAzAAIAcACIAhAIIAKgHIAIgCQAGAAAFAEQAEAEAFAJQAIAPAFAPQAFAQAAAMQAAAJgEAEQgEAFgHgBQgMAAgNgRIgDgEQgOgTgQgIQgQgIgUAAQgaAAgQAMQgPAMAAAWQAAAUANAOQAMANA0AWIAKAEQArASATAQQANANAHAQQAHARAAASQAAAygiAcQgjAbg8AAQgdAAgbgGg");
	this.shape_10.setTransform(-125.4,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.savorysides, new cjs.Rectangle(-141.5,-30.7,283,61.4), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.foryourfeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZBJQgFgCAAgDIAFgJIAFgIIAOgaQAFgMAAgFIgCgHIgIgEQgMgEgGgJQgGgJAAgNQAAgQAKgLQAKgKAPAAQAPAAALAOQAKAOAAAWQAAAQgGARQgGASgQAZIgMATQgGAGgEAAQgHAAgEgDg");
	this.shape.setTransform(155.6,18.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMCSQgNgFgIgIQgIgHgEgOQgEgNAAgkIAAiBIgVAAIgIgCIgCgGIAAgGQAAgHAagXIAKgIIAJgIQAZgWAJAAIAHACQACACABAEIAAAtIA2AAQAFAAADACQACADAAAGIAAAGQAAAHgCADQgDACgFAAIgzAAIgDACIgBAFIAAB4QgBAfAGAIQAFAIAOAAQAIAAAMgEIARgEQAFAAADADQADADABAFQgBANgTANQgWAMgaAAQgOAAgLgDg");
	this.shape_1.setTransform(139.9,3.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_2.setTransform(120.7,5.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AArBxIgNgMIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgUQAcgWAyAAQAMAAAGAEQAGADAAAJQAAANgRABQgXgBgPAMQgOAMAAAVQAAASAMAMQANAMAVAAQAXAAAKgLQAKgKAAgaIAAhbQAAgVgJgLQgJgMgRAAQgLAAgLAGQgKAFgJAKIgFAHQgPASgQAAQgKAAgGgFQgFgHAAgKQAAgXAcgQQAcgPAsAAQAaAAATAHQATAHALAOQAHAIADAPQADAQAAAiIAABNQAAANACAIQADAGAFACIAHABQAPAEAAAJQAAAMgQAJQgQAJgWAAQgKAAgMgNg");
	this.shape_3.setTransform(97.8,5.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhOBbQgjgjABg0QgBg4AkgkQAkglA2AAQAuAAAcAbQAbAaAAAtQAAAPgFAFQgEAFgSAAIhcAAQgIAAgFgEQgEgEAAgHQAAgGAEgDQAFgEAIAAIAxAAIANgCQADgCAAgFQAAgXgQgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlAUAbQASAcAeAAQASAAANgEQAMgEALgIIAJgHQAMgKAHAAQAFAAAEADQADAEABAFQAAAFgHAJQgFAIgLAJQgVARgTAIQgUAHgXAAQgyAAgjgjg");
	this.shape_4.setTransform(71.8,5.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ah6CsQgNgEAAgKQAAgJAMgGQANgFADgDQADgFACglIAChdIgChZQgDglgCgFQgDgDgMgFQgNgFAAgKQAAgKALgEQALgDApAAICUAAIAXgCIANgDIAGACIAEADQAFAKAFAQQAEARAAALQAAALgEAGQgEAGgHAAQgIAAgKgRIgIgMQgFgHgLgEQgKgDgQAAIgiAAQgWAAgMACQgMADgEAGQgEAEgCAQIgCAuIAAAUQAAALACADQACADAHAAIAnAAQATAAAIgFQAHgGACgPIABgFQAEgZANAAQAKABAEANQAEAMAAAvQAAAtgEAOQgEAMgKAAQgNAAgEgaIgBgDQgCgQgHgFQgIgFgTgBIgnAAQgGABgDAEQgCADAAAQIAAATIACBDQABAPAFADIAKAGQAPAFAAAKQAAALgNADQgOAFglAAQgnAAgNgFg");
	this.shape_5.setTransform(44.8,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEADgIQACgIAAgSIAAgQIgBgUIAAgOQAAgsgBgNQgCgOgFgDIgLgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAhgKIAVgFQANAAADAhIABAFIABABQAMgTAOgLQANgKAOAAQARAAAKAKQAKAKAAARQAAARgHAKQgIAJgOAAIgMgCIgKgHIgGgKQgDgGgCAAQgRAAgGAXQgGAXAABJQAAAVACALQADAKAGADIAKADQAOAFAAAKQAAAJgNAEQgOAEggAAQglAAgMgEg");
	this.shape_6.setTransform(7.9,5.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA0B6QgDgDAAgIIAAgSIAAgBIgBAAQgDAAgGAHIgDADQgLALgPAGQgOAGgSABQgSgBgQgGQgQgIgKgMQgMgOgEgTQgFgUAAgzIAAgQIAAgSIAAgEQAAgVgCgFQgDgGgJgDIgKgCQgNgFAAgIQAAgGAFgEQAEgEARgGIAhgJIAagDQAGAAADAEQADAGAAAKIAAAKIgDBaQAAAwALATQAKATAYAAQAbAAAMgYQAMgYAAg7IAAgSQAAgTgCgGQgDgGgJgDIgJgCQgOgFAAgIQAAgFAFgFQAFgEARgGIAggJIAZgDQAIAAADAEQACAFAAALIAAANIgDBkIABAoIABARQACAJAMAFIAFACQANAEAAAIQAAAFgEAFQgEADgLAFIgiALQgRAEgIAAQgHAAgEgEg");
	this.shape_7.setTransform(-16.5,5.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_8.setTransform(-44.2,5.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgyCqQgOgEAAgLQAAgKAPgFIALgFQAHgHABhiIABgWIgdgvIgthIQgPgUgIgFIgMgGQgQgEAAgKQAAgKAMgDQALgEAvgBQAvABALAEQAMADAAAKQAAAKgTAGIgBABIgIAFIgDAHQAAAFALARIAwBLIAqg+QANgXAAgGQAAgHgDgEQgFgDgLgFQgJgEgCgDQgDgEgBgFQAAgKALgDQAJgEAogBQAnABALAEQAJADABAKQAAAKgOAFIgSAJQgLAIgXAkQgXAigjA8IAAAqQACBRAGAGIAKAFQAQAFAAAKQAAALgOAEQgNAFgmgBQglABgNgFg");
	this.shape_9.setTransform(-73.3,0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhIB4QgMgEAAgLQAAgIAMgEIAGgDQAGgEACgIQADgIAAgSIAAgQIgBgUIAAgOQAAgsgBgNQgCgOgGgDIgLgEQgOgEAAgJQAAgFAEgEQAFgEALgFIAggKIAWgFQALAAAFAhIAAAFIACABQAMgTANgLQAOgKAOAAQAQAAAKAKQAKAKAAARQAAARgIAKQgIAJgNAAIgNgCIgJgHIgGgKQgCgGgDAAQgRAAgHAXQgFAXAABJQAAAVACALQADAKAGADIAKADQAPAFAAAKQAAAJgOAEQgNAEghAAQglAAgLgEg");
	this.shape_10.setTransform(-110.9,5.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_11.setTransform(-134.3,5.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhDCtQgMgDAAgLQAAgHALgEIAGgDQAGgDADgIQACgIAAgVIAAgWIAAh0IgbAAQgGAAgCgDQgCgCAAgIIAAgFQAAgGACgCQADgDAFgBIAaAAIgDgTIgBgRQAAgkAXgVQAWgUAnAAQAbAAARAMQARANAAATQAAALgGAGQgGAGgMAAQgHAAgGgDQgHgEgEgGIgEgJQgJgRgOAAQgJgBgFAHQgGAFAAAKIAGAbQAEAVABAQIAjAAQAGAAACADQACACAAAHIAAAFQAAAHgCADQgCADgGAAIgjAAIAAB7QAAAfACAKQACAJAFACIAJAEQAPAFAAAJQAAAJgMAFQgMADgiAAQgkAAgLgEg");
	this.shape_12.setTransform(-152.7,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.foryourfeast, new cjs.Rectangle(-163.8,-30.7,327.6,61.4), null);


(lib.Path = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ap8XiQklh8jijiQjjjih7kmQiBkwAAlMQAAlMCBkvQB7kmDjjiQDijiElh8QExiBFLAAQFMAAExCBQElB8DiDiQDiDiB9EmQCAEvAAFMQAAFMiAEwQh9EmjiDiQjiDiklB8QkxCBlMAAQlLAAkxiBg");
	this.shape.setTransform(163.5,163.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path, new cjs.Rectangle(0,0,327,327), null);


(lib.findanevent = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHA5IAAhjIgkAAIAAgOIBXAAIAAAOIgkAAIAABjg");
	this.shape.setTransform(55.7,0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAcA5Ig7hcIAAAAIAABcIgQAAIAAhxIAUAAIA6BaIABAAIAAhaIAQAAIAABxg");
	this.shape_1.setTransform(45,0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgkA5IAAhxIBHAAIAAAOIg4AAIAAAiIA1AAIAAANIg1AAIAAAmIA6AAIAAAOg");
	this.shape_2.setTransform(34.4,0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGA5IgthxIASAAIAhBcIABAAIAihcIARAAIgtBxg");
	this.shape_3.setTransform(24.1,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglA5IAAhxIBIAAIAAAOIg4AAIAAAiIA0AAIAAANIg0AAIAAAmIA7AAIAAAOg");
	this.shape_4.setTransform(14.5,0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAcA5Ig7hcIgBAAIAABcIgPAAIAAhxIAVAAIA5BaIABAAIAAhaIAQAAIAABxg");
	this.shape_5.setTransform(-0.8,0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAmA5IgLgcIg1AAIgLAcIgSAAIAxhxIAOAAIAwBxgAAUAPIgUg0IgUA0IAoAAg");
	this.shape_6.setTransform(-12.6,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgxA5IAAhxIAmAAQALAAAKAEQALADAJAHQAJAHAFAKIAFAMQABAHAAAGQAAAHgBAHIgFALIgGAKIgIAIQgJAHgLADQgNAEgIAAgAgiArIAVAAQAJAAAJgDQAIgDAGgFQAHgGAEgIIACgIIABgKIgBgJIgCgIQgEgIgHgGQgGgFgIgDQgJgDgJAAIgVAAg");
	this.shape_7.setTransform(-28.1,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAcA5Ig7hcIgBAAIAABcIgPAAIAAhxIAVAAIA5BaIABAAIAAhaIAQAAIAABxg");
	this.shape_8.setTransform(-40.6,0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgHA5IAAhxIAPAAIAABxg");
	this.shape_9.setTransform(-49,0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgiA5IAAhxIBFAAIAAAOIg2AAIAAAkIAzAAIAAAMIgzAAIAAAzg");
	this.shape_10.setTransform(-55.3,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.findanevent, new cjs.Rectangle(-62.3,-11.8,124.7,23.7), null);


(lib.deliciousdessertsbillboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape.setTransform(191.9,5.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMCSQgMgFgJgIQgJgHgDgOQgDgNAAgkIAAiBIgXAAIgGgCIgDgGIAAgGQAAgHAZgXIAKgIIAKgIQAZgWAJAAIAHACQACACAAAEIAAAtIA2AAQAHAAACACQACADAAAGIAAAGQAAAHgDADQgCACgGAAIgxAAIgEACIgCAFIAAB4QABAfAFAIQAFAIAOAAQAIAAAMgEIARgEQAEAAAEADQAEADgBAFQABANgVANQgUAMgaAAQgOAAgMgDg");
	this.shape_1.setTransform(173.2,3.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEACgIQADgIAAgSIAAgQIgBgUIAAgOQAAgsgBgNQgCgOgGgDIgLgEQgOgEAAgJQAAgFAEgEQAFgEALgFIAggKIAWgFQAMAAADAhIABAFIACABQAMgTANgLQAOgKAOAAQAQAAAKAKQAKAKAAARQAAARgHAKQgJAJgNAAIgNgCIgJgHIgGgKQgCgGgDAAQgRAAgHAXQgFAXAABJQAAAVACALQADAKAGADIAKADQAPAFAAAKQAAAJgOAEQgNAEghAAQgkAAgNgEg");
	this.shape_2.setTransform(155.8,5.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhOBbQgjgjAAg0QAAg4AkgkQAkglA1AAQAvAAAcAbQAbAaAAAtQAAAPgFAFQgEAFgSAAIhcAAQgJAAgEgEQgEgEAAgHQAAgGAEgDQAFgEAHAAIAyAAIAMgCQAEgCAAgFQAAgXgQgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlAUAbQATAcAdAAQASAAAMgEQANgEALgIIAJgHQAMgKAHAAQAFAAAEADQAEAEAAAFQgBAFgFAJQgHAIgKAJQgVARgTAIQgUAHgXAAQgyAAgjgjg");
	this.shape_3.setTransform(133.3,5.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_4.setTransform(110,5.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_5.setTransform(89.1,5.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhOBbQgigjAAg0QAAg4AjgkQAkglA2AAQAuAAAbAbQAcAaAAAtQAAAPgEAFQgFAFgSAAIhcAAQgIAAgFgEQgEgEAAgHQAAgGAEgDQAFgEAIAAIAxAAIANgCQADgCgBgFQAAgXgPgQQgQgQgVAAQgdAAgOAZQgOAZAAAkQAAAlAUAbQASAcAeAAQASAAANgEQAMgEALgIIAJgHQANgKAGAAQAFAAAEADQADAEABAFQAAAFgHAJQgFAIgLAJQgVARgTAIQgUAHgXAAQgyAAgjgjg");
	this.shape_6.setTransform(66.1,5.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag0CuIgegBIgUABIgUAAQgeAAgJgEQgJgEAAgKQAAgJAMgFQANgFADgEQADgFACgkIAChdIgChZQgDglgCgFQgDgDgMgFQgNgGAAgJQAAgKAKgEQAKgEAdAAIAVABIAYAAIAggBIAcgBQBZAAAxAvQAxAuAABVQAABUgyAsQgyArhgAAgAg1iJQgLAEgCAIQgEAJgBAcIgCBJIACBcQACAmADAHQACAIAQAFQAQAFAWAAQA3AAAcghQAbgiAAhDQAAhHgfgmQgggmg7AAQgUAAgLAEg");
	this.shape_7.setTransform(34.5,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_8.setTransform(-7.8,5.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AA0B6QgDgDAAgIIAAgSIAAgBIgBAAQgDAAgGAHIgDADQgLALgPAGQgOAGgSABQgSgBgQgGQgQgIgKgMQgMgOgEgTQgFgUAAgzIAAgQIAAgSIAAgEQAAgVgCgFQgDgGgJgDIgKgCQgNgFAAgIQAAgGAFgEQAEgEARgGIAhgJIAagDQAGAAADAEQADAGAAAKIAAAKIgDBaQAAAwALATQAKATAYAAQAbAAAMgYQAMgYAAg7IAAgSQAAgTgCgGQgDgGgJgDIgJgCQgOgFAAgIQAAgFAFgFQAFgEARgGIAggJIAZgDQAIAAADAEQACAFAAALIAAANIgDBkIABAoIABARQACAJAMAFIAFACQANAEAAAIQAAAFgEAFQgEADgLAFIgiALQgRAEgIAAQgHAAgEgEg");
	this.shape_9.setTransform(-32.7,5.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_10.setTransform(-60.4,5.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgqCtQgMgFAAgKQAAgIALgFIAHgDQAGgDADgIQACgIAAgTIAAgQIAAgTIAAgZQAAgmgCgLQgCgMgFgCIgLgEQgPgEAAgJQAAgFAFgFQAFgEAJgEIAlgMIAZgEQAGAAADAEQADAFAAALIAAAPIAAALIgCA8IAAACIgBA7QAAAXACAKQACAJAFADIAJAEQANAEAAAJQAAAJgMAFQgMADgfAAQgkAAgMgDgAgdh5QgLgIABgNQgBgOAMgKQAMgKAQAAQAPAAAKAJQAKAJAAANQAAAOgLAJQgMAJgPAAQgQAAgKgIg");
	this.shape_11.setTransform(-80.9,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhMBbQgigjAAg0QAAg3AkglQAkglA2AAQAnAAAcAVQAcAVAAAbQAAAMgHAHQgIAHgMAAQgNAAgHgGQgHgGgJgUQgHgRgKgHQgJgHgPAAQgbAAgPAVQgQAVAAAlQAAAqAWAbQAWAcAiAAQAMAAALgEQALgDAJgGIAJgHQANgKAHAAQAGAAADADQACACAAAGQAAAGgFAIQgFAJgIAHQgTAQgUAIQgVAIgYAAQgyAAgigjg");
	this.shape_12.setTransform(-100,5.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgqCtQgMgFAAgKQAAgIALgFIAHgDQAGgDACgIQADgIAAgTIAAgQIAAgTIAAgZQAAgmgCgLQgCgMgFgCIgLgEQgPgEAAgJQAAgFAFgFQAEgEALgEIAkgMIAZgEQAGAAAEAEQACAFAAALIAAAPIAAALIgCA8IAAACIgBA7QAAAXACAKQACAJAGADIAJAEQAMAEAAAJQAAAJgMAFQgMADgfAAQglAAgLgDgAgdh5QgKgIAAgNQAAgOALgKQALgKAQAAQAPAAALAJQAKAJAAANQAAAOgLAJQgLAJgQAAQgQAAgKgIg");
	this.shape_13.setTransform(-119.4,0.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgoCuQgMgFAAgKQAAgHAKgFIAMgHQAFgEABgPIACgvIAAglIAAguIAAgTQAAg8gCgRQgDgSgFgDIgPgFQgPgFAAgIQAAgGAFgEQAFgEAQgGIAhgJIAYgDQAIgBADAFQACAEAAAMIAAASQgDBWAABXIABBTQACARAEAEIANAIQAMAEAAAJQAAAJgMAFQgMADggAAQgjAAgMgDg");
	this.shape_14.setTransform(-133.3,0);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhOBbQgigjgBg0QABg4AjgkQAkglA1AAQAvAAAbAbQAbAaAAAtQAAAPgDAFQgFAFgSAAIhcAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQADgEAJAAIAyAAIAMgCQACgCAAgFQAAgXgPgQQgQgQgVAAQgdAAgOAZQgOAZAAAkQAAAlATAbQAUAcAeAAQARAAAMgEQANgEAMgIIAIgHQANgKAGAAQAGAAADADQADAEAAAFQABAFgHAJQgFAIgLAJQgVARgUAIQgTAHgXAAQgyAAgjgjg");
	this.shape_15.setTransform(-152.4,5.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag0CuIgegBIgUABIgUAAQgeAAgJgEQgJgEAAgKQAAgJAMgFQANgFADgEQADgFACgkIAChdIgChZQgDglgCgFQgDgDgMgFQgNgGAAgJQAAgKAKgEQAKgEAdAAIAVABIAYAAIAggBIAcgBQBZAAAxAvQAxAuAABVQAABUgyAsQgyArhgAAgAg1iJQgLAEgCAIQgEAJgBAcIgCBJIACBcQACAmADAHQACAIAQAFQAQAFAWAAQA3AAAcghQAbgiAAhDQAAhHgfgmQgggmg7AAQgUAAgLAEg");
	this.shape_16.setTransform(-184,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.deliciousdessertsbillboard, new cjs.Rectangle(-204.5,-30.7,409,61.4), null);


(lib.date = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhXCiQgYgKAAgPQAAgGADgDQAEgEAFAAIAZAHQAXAHAVAAQAeAAARgTQASgTAAggQgBgVgOgOQgOgOghgMQgSgGgagEQgagGgBgGQABgLAHgeIAUhHIALgeIAGgLIAIgCIAPgBICPAAQgGAhgIAKQgHAJgWAAIhQAAIgUABQgGACgCADQgFAHgFARQgGARAAAOQAAAHAYAEIAeAIQA4AOAWAXQAXAWgBAnQABAygkAgQgiAfg5AAQglAAgYgKg");
	this.shape.setTransform(93.7,4.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgvAZQgIAAgDgCQgDgDAAgHIACgLIAGgNQADgHAEgCQADgDAKAAIAMABIAVAAIApgCIAGAAQAIAAADADQAEADAAAGQAAANgIAMQgHALgLAAIgMgBIgNAAIg1ACIgFAAg");
	this.shape_1.setTransform(58.5,5.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AA4C4QgQAAgCgCQgDgDAAgKIAAhIIiHAAQgTAAgEgDQgFgEAAgKQAAgSBHhhIATgZIASgZQBGhiAVAAQALAAAEAHQAFAGAAASIAADRIAXAAQAJAAAEACQACACAAAHIAAASQAAAGgCACQgEADgJAAIgXAAIAABIQAAAKgDADQgCACgOAAgAgZgaQgeAogbArIB1AAIAAihQggAmgcAog");
	this.shape_2.setTransform(23.1,5.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaAbQgKgMgBgPQABgPAKgKQAMgMAOAAQAQAAAKAMQALAKAAAPQAAAPgLAMQgLALgPAAQgOAAgMgLg");
	this.shape_3.setTransform(-10.1,14.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgZBlQgOgXgihQIgOgjQgRgugLgGIgHgDQgOgFAAgJQAAgKAMgEQAMgEAnAAQAhAAAMAEQAMAEAAAKIgCAIIgEAEIgIADQgKAFAAAFIAFATIATAvIATAuQAGALADAAQADAAAFgGIALgWIAag8QAIgXAAgJIgCgIIgFgGIgHgDQgLgEAAgIQAAgJALgEQALgEAeAAQAZAAAKAEQAKAEAAAJQAAAKgMAEIgIADQgMAFgUAwIgGAPIgKAWQg3B9gPAAQgLAAgNgYg");
	this.shape_4.setTransform(-29.2,5.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_5.setTransform(-55.4,5.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAWBDIgIgKIg0hCIgxg+IgVgXIAAAQIgBAhIAAAXQAABpADAbQADAbAIAAQAHAAAHAGQAGAFAAAHQAAAKgLAEQgMAFgcAAQgdAAgLgFQgLgEAAgKQAAgKANgFQAMgFADgDQADgFACgiIABhgIgBhaQgCgkgDgEQgDgEgMgFQgNgFAAgJQAAgKAKgEQALgEAeAAIAbABIAJAEIAjAqIAwA+IA2BCIAlAtIAZAdIABgKIAAgSIgCh4QgBgxgCgIIgDgFIgGgEQgNgFgEgDQgDgEAAgFQAAgKAKgEQAKgEAgAAQAeAAAKAEQAKAEAAAKQAAAFgCADIgKAGIgFACQgKAEgCAGQgDAKgBAwIgBCQIAAAuIABAeQAAASgDAFQgCAEgHAAQgZAAhWhsg");
	this.shape_6.setTransform(-87.8,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.date, new cjs.Rectangle(-108.9,-30.7,217.9,61.4), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.billboardturkey_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardturkey();
	this.instance.parent = this;
	this.instance.setTransform(-178.5,-110);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardturkey_1, new cjs.Rectangle(-178.5,-110,357,220), null);


(lib.billboardtableatasteof = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardtable();
	this.instance.parent = this;
	this.instance.setTransform(-485,-125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardtableatasteof, new cjs.Rectangle(-485,-125,970,250), null);


(lib.billboardpotatoes_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardpotatoes();
	this.instance.parent = this;
	this.instance.setTransform(-104,-46);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardpotatoes_1, new cjs.Rectangle(-104,-46,208,92), null);


(lib.billboardgreens_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardgreens();
	this.instance.parent = this;
	this.instance.setTransform(-114,-60);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardgreens_1, new cjs.Rectangle(-114,-60,228,120), null);


(lib.billboardcta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AsaDGIAAmKIY1AAIAAGKg");
	this.shape.setTransform(0,0,1.002,0.993);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardcta, new cjs.Rectangle(-79.6,-19.6,159.3,39.2), null);


(lib.billboardcranberries_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardcranberries();
	this.instance.parent = this;
	this.instance.setTransform(-85,-28.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardcranberries_1, new cjs.Rectangle(-85,-28.5,170,57), null);


(lib.billboardcinnamonbuns_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardcinnamonbuns();
	this.instance.parent = this;
	this.instance.setTransform(-58.5,-63);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardcinnamonbuns_1, new cjs.Rectangle(-58.5,-63,117,126), null);


(lib.atasteofbillboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhDCtQgMgDAAgLQAAgHALgEIAGgDQAGgDADgIQACgIAAgVIAAgWIAAh0IgbAAQgGAAgCgDQgCgCAAgIIAAgFQAAgGACgCQADgDAFgBIAaAAIgDgTIgBgRQAAgkAXgVQAWgUAnAAQAbAAARAMQARANAAATQAAALgGAGQgGAGgMAAQgHAAgGgDQgHgEgEgGIgEgJQgJgRgOAAQgJgBgFAHQgGAFAAAKIAGAbQAEAVABAQIAjAAQAGAAACADQACACAAAHIAAAFQAAAHgCADQgCADgGAAIgjAAIAAB7QAAAfACAKQACAJAFACIAJAEQAPAFAAAJQAAAJgMAFQgMADgiAAQgkAAgLgEg");
	this.shape.setTransform(107,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_1.setTransform(84.5,5.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhOBbQgigjgBg0QAAg4AkgkQAjglA2AAQAvAAAbAbQAbAaAAAtQAAAPgDAFQgFAFgSAAIhcAAQgJAAgDgEQgFgEAAgHQAAgGAFgDQADgEAIAAIAzAAIALgCQADgCAAgFQAAgXgPgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlATAbQATAcAfAAQARAAAMgEQANgEAMgIIAIgHQANgKAGAAQAGAAADADQAEAEgBAFQAAAFgFAJQgHAIgKAJQgVARgUAIQgTAHgXAAQgzAAgigjg");
	this.shape_2.setTransform(44.8,5.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgMCSQgMgFgJgIQgJgHgDgOQgDgNgBgkIAAiBIgVAAIgIgCIgBgGIAAgGQAAgHAZgXIAKgIIAJgIQAZgWAJAAIAHACQADACAAAEIAAAtIA2AAQAFAAADACQACADAAAGIAAAGQAAAHgCADQgDACgFAAIgzAAIgDACIgBAFIAAB4QgBAfAGAIQAFAIAOAAQAIAAAMgEIAQgEQAGAAADADQAEADAAAFQAAANgVANQgUAMgbAAQgNAAgMgDg");
	this.shape_3.setTransform(23.6,3.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_4.setTransform(4.4,5.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AArBxIgNgMIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgUQAcgWAyAAQAMAAAGAEQAGADAAAJQAAANgRABQgXgBgPAMQgOAMAAAVQAAASAMAMQANAMAVAAQAXAAAKgLQAKgKAAgaIAAhbQAAgVgJgLQgJgMgRAAQgLAAgLAGQgKAFgJAKIgFAHQgPASgQAAQgKAAgGgFQgFgHAAgKQAAgXAcgQQAcgPAsAAQAaAAATAHQATAHALAOQAHAIADAPQADAQAAAiIAABNQAAANACAIQADAGAFACIAHABQAPAEAAAJQAAAMgQAJQgQAJgWAAQgKAAgMgNg");
	this.shape_5.setTransform(-18.5,5.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgyCrQgOgDAAgLQAAgKAOgFQANgFABgDQADgEACgoIAChyIgBhAIgCgnQgCgGgEgCQgDgCgLAAIgKAAQgQAAgKAEQgJAEgHAKIgHAQIgIAQIgHAHQgEADgEABQgIAAgDgHQgDgGAAgQQAAgfAIgTQAHgUAMAAIACAAQATADAdAAICOAAQAdAAAUgDIADAAQALAAAHAUQAIATAAAfQAAAQgEAGQgDAHgIAAIgIgEIgGgHIgHgQIgIgQQgHgKgKgEQgJgEgRAAIgKAAQgKAAgDACQgFACgBAHIgBAmIgBBAIABByQABAoADAEQADADANAFQANAFAAAKQAAALgOADQgNAFgmAAQglAAgNgFg");
	this.shape_6.setTransform(-47.4,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA0CtQgOgEAAgLQAAgJASgGIADgCQAHgCADgDQADgEAAgGIgFgUIgJgZIgEgIIgEgCIgTgCIgjAAIgVAAQgVAAAAgRQAAgTAWAAIALgBIAZABIAaABIgahCIgXg4IgGAAIgZA8IgZA+IgXA+QgFAOAAAJQAAAHADAFQADAFAHADIAIAEQAQAFAAAKQAAALgMAEQgNAEglAAQglAAgLgEQgNgEAAgLQAAgKAOgFIAKgFQATgLAQgqIAFgOIAihWIAJgVQAjhXAIgkQACgLAGgDQAFgDANAAQAIAAAGADQAFADAFAJIAlBQIAvByIALAcQAbBGARAJIAIADQAQAFAAAKQAAALgPAEQgOAEgrAAQgsAAgOgEg");
	this.shape_7.setTransform(-93.9,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofbillboard, new cjs.Rectangle(-113.8,-30.7,227.7,61.4), null);


(lib.whitelogouse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKgALSMVIgBANQAAAPAKAAIAzAAQAMAAgBAKIAACUQAAAHAGACQADACAKABQAKgBAEgCQAFgCAAgIIgBiTQABgKAMAAIAxAAQALAAAAgSQAAgSgMAAIigAAQgGAAgDAIgADSONIBBBGQAHAHATABQANAAAFgFQAGgFgIgIIhOhWQgJgLAKgHIBAg6QAJgKgMgMQgMgMgNALIhKBEQgFAFgEABQgFADgKAAQgKAAAAgOIAAg2QAAgMgRAAQgMAAgDACQgFACgBAIIAAC1QAAANARAAQAVAAAAgNIAAg7QAAgGADgFQAEgEAFAAQATgBALAKgAhwOXQALAAAFAJIAhAyQAFAIARABQAPAAAEgFQAFgEgFgHIgigzQgEgFAHgHQAPgKAIgIQAOgQAAgYQABgfgVgUQgUgSggAAIhsAAQgJAAAAAIIAAC6QAAAMANAAIAPgBQAKgBAAgHIgBgxQABgEADgDQADgDAEAAgAmQOxQAIAAACAHIANAbQAEAHAPABQAIgBAGgCQAJgDgDgGIhXi7QgFgJgLAAQgMAAgEAKIhaC5QgFAMAWAAQASAAADgHIANgXQAEgLAIAAgArGNkIANBsQAAAFAGADQAFADAEAAQAYAAgBgLIgVi2QgCgIgEgDQgDgCgGAAQgLAAgEAIIg8BPQgHAIgEAAQgEABgGgIIg3hPQgGgIgKAAQgKgBgEAFQgDADgCAJIgVCxQAAAGAGADQAFADAFAAQAUAAACgLIANhpQACgIAEABQAEAAADACIAtA9QAEAHAHAAQAFAAAFgGIAwg/QADgEAEABQAFgBACAHgAGyMaIAACwQAAAOANAAICcAAQAKABAAgSQAAgSgKAAIh6AAQgJAAgBgLIAAgdQAAgLAMAAIBFAAQAKAAAAgRQABgTgLABIhHAAQgJAAgBgKIAAgbQAAgJAJAAIB6AAQAHAAADgGQABgEAAgJQAAgJgBgEQgDgEgGAAIicAAQgNAAAAANgAT4IwQgNAOABASQgBASANANQANANATAAQASAAANgNQANgNAAgSQAAgSgNgOQgNgNgSABQgTgBgNANgAP5JKQAlAMA0AAQBUAAAzgtQAygtAAhJQAAghgMgeQgMgegWgXQgUgVgXgSQgWgRgzgkIgqgdQgbgVgMgSQgJgMAAgXQAAgaARgQQASgPAeAAQAsAAAjAbQAPALAFAGQAHAIAOAVQAKAOAMAAQALABAGgHQAIgFgBgJQABgIgCgEIgUhcQgFgXgTAAQgIAAgKAGQgLAIgIAAIgMgCIgWgEQgjgIgmAAQhGAAgrAlQgrAmAAA+QAAAzAgAmQAUAVARAPIBNA3QBBAsAaAdQAcAfgBAhQABAigaAUQgaAWgpAAQglAAgigSQghgTgWgfIgMgRQgJgLgMAAQgLAAgIAIQgIAIAAALQAAAKACAHIAWBUQAEAQAFAHQAGAGALAAQAJAAALgIQAJgJAJABIASAEgAjRF+QAHAAACALIABADQAYBeBFA1QBHA2BlAAQCCAABMhQQBMhRAAiIQAAiFhMhQQhNhQh+ABQhogBhHA3QhFA1gYBgIAAABQgCALgHAAQgIAAgBgKQgYhhhHg2QhHg3hoABQiBAAhLBQQhLBQAACIQgBCFBMBQQBMBQB+AAQBoAABIg2QBHg2AYhfIAAgBQACgLAGAAIABAAgAFnIeQgGAHAAAKQAAANAJAFQAIAEAUADQBeANBrgBQBFABAxgOQAvgOAlgeQAwglAZg+QAZg9AAhOQAAhFgTg3QgVg5glgmQgngng1gSQg1gShOAAQhrAAheANQgUADgIAEQgJAFAAANQAAAJAGAIQAFAGAJABIARAAQAKAAAFALQADAKgBAXIAAF5QABAYgDAKQgFALgKAAIgRAAQgJAAgFAHgAyyIfQgHAHABAKQgBAOAJAFQAJAGAWAAICcAAQAYAAAJgGQAJgFAAgOQAAgKgHgHQgGgGgKAAIgTAAQgMAAgGgMQgCgFAAgbIgBiLQAAgZAJgFQAEgEAeAAIBGAAQAaAAAIAEQAHADACANIABAFQAEAWATABQANgBAGgIQAFgKAAgWIAAhHQAAgWgFgJQgGgJgNAAQgUAAgDAVIgBAGQgBAMgIAEQgHADgbAAIhGAAQgeAAgEgDQgJgFAAgaIAAhlQABghAIgJQAJgJAiAAIBtAAQAgAAANAEQAOAFAGAPQAFAOADAFQAIAOAOAAQAMAAAFgJQAGgJgEgQIgMg8QgFgUgZgBIlwAAQgWABgIAFQgJAGAAAOQgBAJAHAHQAHAHAIAAIASAAQAEAAAEAEQAEADABAGQAEAKAAAXIAAF8QAAAXgDAJQgEAMgKAAIgSAAQgJAAgGAGgACorXQACAKgJADQgpAOgmATQgmATgZASQg5AoggBCQgfBEAABaQgBCLBPBTQBOBUCEAAQCHAABQhVQBPhUAAiOQAAilhohNQg7gsg4AGQghAEgFAUQgFATAbAKQA2AUAZA8QAXA3ABBfQAABxgrBBQgrBChKAAQhLAAgphBQgrg/AAhyQAAhQAQg0QASg+AwgvQAegdBHgjQA9gfAigrQATgZABgVQACgTgQgEQgMgEgNANIgZAWQguAeg4gRQgvgPgjgoQgcgggogIQgcgGgfAHQgLADgEgHQgCgHAKgIQAbgVArACQAvACAfAcQAdAbAhAPQAjARAagGQARgDAAgOQABgOgTgHQgegLgng1Qgmg0g0gQQhOgWhLA9QhDA3gXBWQgGAXAMALQAMALAUgKQA7gZAuAWQAJAEAhAVQAcARAWAJQAsARA7gLIAGAAQAIAAACAHgAvDlPIBJDYQAHAXALAJQALAKATAAQATAAALgLQAKgLAJggICImzQAGgWAHgJQAIgJALgCQAkgEgBAwIAAF+QAAAbgCAHQgBAEgFADQgEADgFAAIgQAAQgJAAgHAHQgGAHgBAJQAAAOAJAGQAJAFAVAAICbAAQAVAAAIgFQAHgFABgOQAAgKgGgHQgGgHgJAAIgQAAQgLAAgFgKQgCgKAAgYIAAiBQgBgeAGgGQAFgHAYABIBzAAQAYgBAHAIQACAEABAGIAAAeIAAB8QAAAbgCAHQgGAKgJAAIgRAAQgIAAgHAHQgGAHAAAJQgBAOAJAGQAIAFAWAAICaAAQAWAAAJgFQAJgGAAgOQAAgJgHgHQgGgHgKAAIgRAAQgEAAgFgDQgEgDgBgEQgEgKAAgYIAAl+QAAgXAEgKQABgEAEgDQAFgEAEAAIARAAQAKABAGgHQAHgHAAgKQgBgOgIgFQgJgGgWAAIiaAAQgWAAgJAGQgJAFABAOQgBAKAHAHQAGAHAKgBIARAAQAKAAAFALQACAGAAAbIAABpIAAAeQgBAHgCADQgHAHgYAAIhzAAQgYAAgFgGQgGgHABgdIAAhuQAAgYACgJQAFgLALAAIAQAAQAJABAGgHQAGgHAAgKQAAgOgIgFQgIgGgVAAIkmAAQgRAAgIAGQgIAFAAANQAAAWAcABQAeAEAAATQAAAIgEAMIheE7QgCAFgEABQgEAAgCgGIhfksQgIgZgBgLQAAgMAHgEQAFgFARgCQAcgFgBgSQAAgXgcAAIinAAQgdAAgBAaQABAJAFAFQAGAFANADQAOAFAHADQAHAFADAKIAmBtQAHAYgJAZIg+C3QgCAFgEAAQgFABgCgFIh0lIQgCgLAAgIQAAgKAGgFQAGgEAOgCQARgBAGgGQAIgEgBgLQAAgXgcAAIiuAAQgdAAAAAWQAAALAFAEQAFAGANACQAVAFAHAGQAHAIAJAaICnG/QAJAXALAKQAKAJATAAQAQAAAMgJQAIgIAJgZIBOjYQABgGAEAAQAFAAABAGgAOkiCQgGAHAAAJQAAAOAJAGQAHAFAWABIFigBQAaAAAFgVIANhCQADgQgFgJQgEgJgNABQgPAAgHAPIgIAQQgPAggvAAIhUAAQgkAAgPgGQgKgEgDgLQgDgLAAgiIAAhsQAAgZAIgFQAEgDAfAAIAmAAQAbAAAHADQAIADACANIAAAFQAEAXAUAAQANAAAGgJQAEgJAAgWIAAhIQAAgVgEgJQgGgKgNAAQgUAAgEAWIAAAFQgCANgHADQgIADgbAAIgmAAQgfAAgEgCQgIgGAAgaIAAhkQAAgiAIgJQAJgIAjgBIBQAAQAfABANAEQAPAFAFAPQAGAQADACQAHAOAOAAQANAAAEgJQAGgJgEgQIgMg7QgFgVgZAAIlTAAQgVAAgJAGQgJAFAAAOQAAAJAGAIQAIAGAIAAIARAAQAEAAAEAEQAEAEACAFQADAIAAAaIAAF7QAAAagDAIQgCAEgDADQgEAEgFAAIgRAAQgJAAgGAGgAHyiCQgGAHAAAJQAAAOAJAGQAIAFAVAAIE/AAQAaAAAFgVIAMhCQAEgQgFgJQgFgJgMABQgPAAgIAPIgHAQQgQAgguAAIgxAAQgZAAgMgCQgMgBgGgFQgIgFgCgJQgCgJAAgdIAAllQABgbACgFQADgMAOAAIATAAQAJABAHgHQAGgHABgKQgBgOgIgFQgKgGgXAAIicAAQgWAAgJAGQgJAFAAAOQAAAKAHAHQAGAHAKgBIARAAQALAAADAMQADAHAAAZIAAGBQAAAXgDAIQgBAEgEADQgFAEgEAAIgRAAQgJAAgGAGg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAaQgKgLAAgPQAAgOAKgKQAKgLAOABQAPgBAKALQAKAKAAAOQAAAPgKALQgKAJgPABQgOgBgKgJgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgVIAFAAIAOAVIAKAAg");
	this.shape_1.setTransform(130.4,59.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(-11.1,85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(130.6,58);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QAog/BHAAQBGAAAoA/QAqBAAABqQAABrgpBAQgpA/hFAAQhIAAgog+g");
	this.shape_4.setTransform(-48.8,30.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgyQABgDADAAQADAAACADIAZAzQABADgCACQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-44.3,88.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(64.5,30);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QApg/BGAAQBFAAAqA/QApBAAABqQAABrgpBAQgpA/hGAAQhGAAgpg+g");
	this.shape_7.setTransform(6.9,30.3);

	this.instance = new lib.Path();
	this.instance.parent = this;
	this.instance.setTransform(0,0.1,1,1,0,0,0,163.5,163.5);
	this.instance.alpha = 0.59;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitelogouse, new cjs.Rectangle(-175,-175,350,350), null);


// stage content:
(lib.billboardatasteoffive = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_48 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_356 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(48).call(this.frame_48).wait(308).call(this.frame_356).wait(3));

	// white-logo
	this.instance = new lib.whitelogouse();
	this.instance.parent = this;
	this.instance.setTransform(851.8,50.7,0.414,0.414,0,0,0,0,0.1);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({regY:0,scaleX:0.03,scaleY:0.03,y:56.7},0).to({regX:0.1,scaleX:0.47,scaleY:0.47,x:851.9,alpha:1},6).to({scaleX:0.41,scaleY:0.41,x:851.8},7).wait(337));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(486.2,125.3,4.708,0.381,0,0,0,0.3,0.8);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(359));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(486.8,125.1,5.906,0.417,0,0,0,0.4,0.2);
	this.instance_1.filters = [new cjs.ColorFilter(1, 1, 1, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.1,regY:0.4,x:488.7,alpha:0},9).wait(350));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask.setTransform(351,120.6);

	// a-taste-of
	this.instance_2 = new lib.atasteofbillboard();
	this.instance_2.parent = this;
	this.instance_2.setTransform(143.1,84.2);
	this.instance_2.alpha = 0;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({x:-89.9,y:81.9},0).to({x:163.1,y:84.2,alpha:1},10,cjs.Ease.get(1)).to({x:143.1},6,cjs.Ease.get(1)).wait(184).to({alpha:0},5).wait(145));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_1.setTransform(351,120.6);

	// whole-foods-market
	this.instance_3 = new lib.wholefoodsmarket();
	this.instance_3.parent = this;
	this.instance_3.setTransform(262.3,137.6);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(25).to({x:-209.1},0).to({x:282.3,alpha:1},10,cjs.Ease.get(1)).to({x:262.3},6,cjs.Ease.get(1)).wait(46).to({alpha:0},5).wait(267));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	var mask_2_graphics_87 = new cjs.Graphics().p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:351,y:120.6}).wait(87).to({graphics:mask_2_graphics_87,x:351,y:120.6}).wait(272));

	// Savory Sides
	this.instance_4 = new lib.savorysides();
	this.instance_4.parent = this;
	this.instance_4.setTransform(170.8,137.6);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(87).to({x:-117.6},0).to({x:190.8,alpha:1},10,cjs.Ease.get(1)).to({x:170.8},6,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(221));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_0 = new cjs.Graphics().p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	var mask_3_graphics_87 = new cjs.Graphics().p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:mask_3_graphics_0,x:351,y:120.6}).wait(87).to({graphics:mask_3_graphics_87,x:351,y:120.6}).wait(272));

	// delicious-desserts
	this.instance_5 = new lib.deliciousdessertsbillboard();
	this.instance_5.parent = this;
	this.instance_5.setTransform(233.8,137.6);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(133).to({x:-180.6},0).to({x:253.8,alpha:1},10,cjs.Ease.get(1)).to({x:233.8},6,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(175));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	var mask_4_graphics_0 = new cjs.Graphics().p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	var mask_4_graphics_87 = new cjs.Graphics().p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");

	this.timeline.addTween(cjs.Tween.get(mask_4).to({graphics:mask_4_graphics_0,x:351,y:120.6}).wait(87).to({graphics:mask_4_graphics_87,x:351,y:120.6}).wait(272));

	// thanksgiving
	this.instance_6 = new lib.thanksgiving();
	this.instance_6.parent = this;
	this.instance_6.setTransform(178.8,137.6);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(179).to({x:-125.6},0).to({x:198.8,alpha:1},10,cjs.Ease.get(1)).to({x:178.8},6,cjs.Ease.get(1)).wait(14).to({alpha:0},5).wait(145));

	// mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("EgvPATTMAAAgmlMBmGAAAMAAAAmlg");
	mask_5.setTransform(351.1,120.6);

	// cta
	this.instance_7 = new lib.findanevent();
	this.instance_7.parent = this;
	this.instance_7.setTransform(110.9,195.9);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(47).to({x:-55.7},0).to({x:131.5,alpha:1},10,cjs.Ease.get(1)).to({x:110.9},6,cjs.Ease.get(1)).wait(296));

	// mask (mask)
	var mask_6 = new cjs.Shape();
	mask_6._off = true;
	var mask_6_graphics_0 = new cjs.Graphics().p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	var mask_6_graphics_47 = new cjs.Graphics().p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");

	this.timeline.addTween(cjs.Tween.get(mask_6).to({graphics:mask_6_graphics_0,x:351,y:120.6}).wait(47).to({graphics:mask_6_graphics_47,x:351,y:120.6}).wait(312));

	// cta-rectangle
	this.instance_8 = new lib.billboardcta();
	this.instance_8.parent = this;
	this.instance_8.setTransform(111.5,195.7);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_6;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(47).to({x:-55.7},0).to({x:131.5,alpha:1},10,cjs.Ease.get(1)).to({x:111.5},6,cjs.Ease.get(1)).wait(296));

	// mask (mask)
	var mask_7 = new cjs.Shape();
	mask_7._off = true;
	mask_7.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_7.setTransform(351,120.6);

	// tasting-event-near-you
	this.instance_9 = new lib.tastingeventnearyou();
	this.instance_9.parent = this;
	this.instance_9.setTransform(175.3,38.3);
	this.instance_9.alpha = 0;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_7;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(223).to({x:-122.1},0).to({x:195.3,alpha:1},10,cjs.Ease.get(1)).to({x:175.3},6,cjs.Ease.get(1)).wait(120));

	// mask (mask)
	var mask_8 = new cjs.Shape();
	mask_8._off = true;
	mask_8.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_8.setTransform(351,120.6);

	// try-new-flavors
	this.instance_10 = new lib.trynewflavors();
	this.instance_10.parent = this;
	this.instance_10.setTransform(208.7,84.2);
	this.instance_10.alpha = 0;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_8;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(233).to({x:-155.5,y:81.9},0).to({x:228.7,y:84.2,alpha:1},10,cjs.Ease.get(1)).to({x:208.7},6,cjs.Ease.get(1)).wait(110));

	// mask (mask)
	var mask_9 = new cjs.Shape();
	mask_9._off = true;
	mask_9.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_9.setTransform(351,120.6);

	// for-your-feast
	this.instance_11 = new lib.foryourfeast();
	this.instance_11.parent = this;
	this.instance_11.setTransform(193.1,137.6);
	this.instance_11.alpha = 0;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_9;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(243).to({x:-139.9},0).to({x:213.1,alpha:1},10,cjs.Ease.get(1)).to({x:193.1},6,cjs.Ease.get(1)).wait(100));

	// turkey
	this.instance_12 = new lib.billboardturkey_1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(763.5,140);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(55).to({alpha:1},10).wait(294));

	// cinnamon-buns
	this.instance_13 = new lib.billboardcinnamonbuns_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(911.5,63);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(65).to({alpha:1},10).wait(284));

	// brussel-sprouts
	this.instance_14 = new lib.billboardgreens_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(559,60);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(42).to({alpha:1},10).wait(307));

	// cranberries
	this.instance_15 = new lib.billboardcranberries_1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(452,221.5);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(29).to({alpha:1},10).wait(320));

	// potatoes
	this.instance_16 = new lib.billboardpotatoes_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(238,204);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(19).to({alpha:1},10).wait(330));

	// date
	this.instance_17 = new lib.date();
	this.instance_17.parent = this;
	this.instance_17.setTransform(479.2,137.6);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(264).to({alpha:1},10,cjs.Ease.get(1)).wait(85));

	// table
	this.instance_18 = new lib.billboardtableatasteof();
	this.instance_18.parent = this;
	this.instance_18.setTransform(485,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(359));

	// trace
	this.instance_19 = new lib.billboardgetinspiredtrace();
	this.instance_19.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(359));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(484.6,103.1,970.4,271.9);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 970,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;